### ISSUE TITLE
can anyone tell me what's going wrong in this build?

### ISSUE THREAD

**Issue by decorumos** [VeltTechnologies/graphene-desktop#1]
gcc -fPIC -shared -Wall -I. -pthread -D_REENTRANT -pthread -I/usr/include/libpeas-1.0 -I/usr/include/gobject-introspection-1.0 -I/usr/include/accountsservice-1.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/clutter-1.0 -I/usr/include/cogl -I/usr/include/atk-1.0 -I/usr/include/cogl -I/usr/include/libdrm -I/usr/include/json-glib-1.0 -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircommon -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/mutter -I/usr/include/gsettings-desktop-schemas -lpeas-1.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lgirepository-1.0 -laccountsservice -lpulse-mainloop-glib -lpulse -lmutter -lgtk-3 -lclutter-1.0 -lcogl-path -latk-1.0 -lcogl-pango -lcogl -lgmodule-2.0 -pthread -lwayland-egl -lgbm -ldrm -lEGL -lXrandr -ljson-glib-1.0 -lgio-2.0 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lgdk_pixbuf-2.0 -lcairo-gobject -lcairo -lgobject-2.0 -lglib-2.0 -lwayland-cursor -lwayland-client -lxkbcommon -lwayland-server -lXext -lXdamage -lXfixes -lXcomposite -lXi -lX11 -DVDE_DATA_DIR=\"/usr/share/graphene\" lib/panel.c lib/applet-extension.c lib/system-volume-control.c lib/materialbox.c -o lib/libvos.so
lib/panel.c: In function ‘vos_panel_class_init’:
lib/panel.c:66:134: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
 lass _object_class = G_OBJECT_CLASS (klass); object_class->finalize = vos_panel
                                                                     ^
lib/panel.c: In function ‘notification_info_free’:
lib/panel.c:629:10: warning: passing argument 1 of ‘g_free’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   g_free(info->appName);
          ^
In file included from /usr/include/glib-2.0/glib/glist.h:32:0,
                 from /usr/include/glib-2.0/glib/ghash.h:33,
                 from /usr/include/glib-2.0/glib.h:50,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from lib/panel.h:24,
                 from lib/panel.c:20:
/usr/include/glib-2.0/glib/gmem.h:71:7: note: expected ‘gpointer {aka void *}’ but argument is of type ‘const gchar \* {aka const char *}’
 void  g_free           (gpointer  mem);
       ^
lib/panel.c:630:10: warning: passing argument 1 of ‘g_free’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   g_free(info->icon);
          ^
In file included from /usr/include/glib-2.0/glib/glist.h:32:0,
                 from /usr/include/glib-2.0/glib/ghash.h:33,
                 from /usr/include/glib-2.0/glib.h:50,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from lib/panel.h:24,
                 from lib/panel.c:20:
/usr/include/glib-2.0/glib/gmem.h:71:7: note: expected ‘gpointer {aka void *}’ but argument is of type ‘const gchar \* {aka const char *}’
 void  g_free           (gpointer  mem);
       ^
lib/panel.c:631:10: warning: passing argument 1 of ‘g_free’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   g_free(info->summary);
          ^
In file included from /usr/include/glib-2.0/glib/glist.h:32:0,
                 from /usr/include/glib-2.0/glib/ghash.h:33,
                 from /usr/include/glib-2.0/glib.h:50,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from lib/panel.h:24,
                 from lib/panel.c:20:
/usr/include/glib-2.0/glib/gmem.h:71:7: note: expected ‘gpointer {aka void *}’ but argument is of type ‘const gchar \* {aka const char *}’
 void  g_free           (gpointer  mem);
       ^
lib/panel.c:632:10: warning: passing argument 1 of ‘g_free’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   g_free(info->body);
          ^
In file included from /usr/include/glib-2.0/glib/glist.h:32:0,
                 from /usr/include/glib-2.0/glib/ghash.h:33,
                 from /usr/include/glib-2.0/glib.h:50,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from lib/panel.h:24,
                 from lib/panel.c:20:
/usr/include/glib-2.0/glib/gmem.h:71:7: note: expected ‘gpointer {aka void *}’ but argument is of type ‘const gchar \* {aka const char *}’
 void  g_free           (gpointer  mem);
       ^
lib/panel.c:633:10: warning: passing argument 1 of ‘g_free’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   g_free(info->category);
          ^
In file included from /usr/include/glib-2.0/glib/glist.h:32:0,
                 from /usr/include/glib-2.0/glib/ghash.h:33,
                 from /usr/include/glib-2.0/glib.h:50,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from lib/panel.h:24,
                 from lib/panel.c:20:
/usr/include/glib-2.0/glib/gmem.h:71:7: note: expected ‘gpointer {aka void *}’ but argument is of type ‘const gchar \* {aka const char *}’
 void  g_free           (gpointer  mem);
       ^
lib/panel.c: In function ‘init_notifications’:
lib/panel.c:648:65: warning: passing argument 4 of ‘g_hash_table_new_full’ from incompatible pointer type [-Wincompatible-pointer-types]
   self->Notifications = g_hash_table_new_full(NULL, NULL, NULL, notification_in
                                                                 ^
In file included from /usr/include/glib-2.0/glib.h:50:0,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from lib/panel.h:24,
                 from lib/panel.c:20:
/usr/include/glib-2.0/glib/ghash.h:60:13: note: expected ‘GDestroyNotify {aka void (_)(void _)}’ but argument is of type ‘void (_)(NotificationInfo _) {aka void (_)(struct <anonymous> _)}’
 GHashTable_ g_hash_table_new_full          (GHashFunc       hash_func,
             ^
lib/panel.c:652:11: warning: passing argument 5 of ‘g_bus_own_name’ from incompatible pointer type [-Wincompatible-pointer-types]
     NULL, notification_server_name_acquired, notification_server_name_lost,
           ^
In file included from /usr/include/glib-2.0/gio/gio.h:57:0,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:28,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from lib/panel.h:24,
                 from lib/panel.c:20:
/usr/include/glib-2.0/gio/gdbusnameowning.h:76:7: note: expected ‘GBusNameAcquiredCallback {aka void (_)(struct _GDBusConnection *, const char *, void *)}’ but argument is of type ‘void (_)(GDBusConnection _, const gchar *, VosPanel *) {aka void (_)(struct _GDBusConnection _, const char *, struct _VosPanel *)}’
 guint g_bus_own_name                 (GBusType                  bus_type,
       ^
lib/panel.c:652:46: warning: passing argument 6 of ‘g_bus_own_name’ from incompatible pointer type [-Wincompatible-pointer-types]
     NULL, notification_server_name_acquired, notification_server_name_lost,
                                              ^
In file included from /usr/include/glib-2.0/gio/gio.h:57:0,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:28,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from lib/panel.h:24,
                 from lib/panel.c:20:
/usr/include/glib-2.0/gio/gdbusnameowning.h:76:7: note: expected ‘GBusNameLostCallback {aka void (_)(struct _GDBusConnection _, const char *, void *)}’ but argument is of type ‘void (_)(GDBusConnection _, const gchar *, VosPanel *) {aka void (_)(struct _GDBusConnection _, const char *, struct _VosPanel *)}’
 guint g_bus_own_name                 (GBusType                  bus_type,
       ^
lib/panel.c: In function ‘notification_server_name_acquired’:
lib/panel.c:662:60: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   static const GDBusInterfaceVTable interfaceCallbacks = { on_notification_serv
                                                            ^
lib/panel.c:662:60: note: (near initialization for ‘interfaceCallbacks.method_call’)
In file included from /usr/include/glib-2.0/gobject/gobject.h:28:0,
                 from /usr/include/glib-2.0/gobject/gbinding.h:29,
                 from /usr/include/glib-2.0/glib-object.h:23,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:28,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from lib/panel.h:24,
                 from lib/panel.c:20:
lib/panel.c: In function ‘show_notification’:
/usr/include/glib-2.0/gobject/gsignal.h:475:59: warning: passing argument 3 of ‘g_signal_connect_data’ from incompatible pointer type [-Wincompatible-pointer-types]
     g_signal_connect_data ((instance), (detailed_signal), (c_handler), (data), 
                                                           ^
lib/panel.c:757:5: note: in expansion of macro ‘g_signal_connect’
     g_signal_connect(info->window, "button_press_event", on_notification_clicke
     ^
/usr/include/glib-2.0/gobject/gsignal.h:388:9: note: expected ‘GCallback {aka void (_)(void)}’ but argument is of type ‘gboolean (_)(GtkWindow *, GdkEventButton *, NotificationInfo *) {aka int (_)(struct _GtkWindow _, struct _GdkEventButton *, struct <anonymous> *)}’
 gulong  g_signal_connect_data        (gpointer    instance,
         ^
lib/panel.c:778:12: warning: passing argument 1 of ‘g_free’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
     g_free(bodyMarkup);
            ^
In file included from /usr/include/glib-2.0/glib/glist.h:32:0,
                 from /usr/include/glib-2.0/glib/ghash.h:33,
                 from /usr/include/glib-2.0/glib.h:50,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from lib/panel.h:24,
                 from lib/panel.c:20:
/usr/include/glib-2.0/glib/gmem.h:71:7: note: expected ‘gpointer {aka void *}’ but argument is of type ‘const gchar \* {aka const char *}’
 void  g_free           (gpointer  mem);
       ^
lib/panel.c:794:59: warning: passing argument 2 of ‘g_timeout_add’ from incompatible pointer type [-Wincompatible-pointer-types]
     info->timeoutSourceTag = g_timeout_add(info->timeout, show_notification_rem
                                                           ^
In file included from /usr/include/glib-2.0/glib/giochannel.h:33:0,
                 from /usr/include/glib-2.0/glib.h:54,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from lib/panel.h:24,
                 from lib/panel.c:20:
/usr/include/glib-2.0/glib/gmain.h:560:10: note: expected ‘GSourceFunc {aka int (_)(void _)}’ but argument is of type ‘gboolean (_)(NotificationInfo _) {aka int (_)(struct <anonymous> _)}’
 guint    g_timeout_add              (guint           interval,
          ^
lib/panel.c: In function ‘update_notification_windows’:
lib/panel.c:818:52: warning: passing argument 2 of ‘g_list_sort’ from incompatible pointer type [-Wincompatible-pointer-types]
   notificationList = g_list_sort(notificationList, notification_compare_func);
                                                    ^
In file included from /usr/include/glib-2.0/glib/ghash.h:33:0,
                 from /usr/include/glib-2.0/glib.h:50,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from lib/panel.h:24,
                 from lib/panel.c:20:
/usr/include/glib-2.0/glib/glist.h:136:10: note: expected ‘GCompareFunc {aka int (_)(const void _, const void *)}’ but argument is of type ‘gint (_)(const NotificationInfo _, const NotificationInfo *) {aka int (_)(const struct <anonymous> _, const struct <anonymous> *)}’
 GList_   g_list_sort                    (GList            _list,
          ^
lib/materialbox.c: In function ‘vos_material_box_class_init’:
lib/materialbox.c:71:36: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
   widgetClass->get_preferred_width = vos_material_box_get_preferred_width;
                                    ^
lib/materialbox.c:72:37: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
   widgetClass->get_preferred_height = vos_material_box_get_preferred_height;
                                     ^
lib/materialbox.c:73:30: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
   widgetClass->size_allocate = vos_material_box_size_allocate;
                              ^
lib/materialbox.c:74:21: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
   widgetClass->draw = vos_material_box_draw;
                     ^
lib/materialbox.c:75:25: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
   widgetClass->show_all = vos_material_box_show_all;
                         ^
lib/materialbox.c:77:23: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
   containerClass->add = vos_material_box_add;
                       ^
lib/materialbox.c:78:26: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
   containerClass->remove = vos_material_box_remove;
                          ^
lib/materialbox.c:79:26: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
   containerClass->forall = vos_material_box_forall;
                          ^
lib/materialbox.c:80:30: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
   containerClass->child_type = vos_material_box_child_type;
                              ^
lib/materialbox.c:81:38: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
   containerClass->set_child_property = vos_material_box_set_child_property;
                                      ^
lib/materialbox.c:82:38: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
   containerClass->get_child_property = vos_material_box_get_child_property;
                                      ^
lib/materialbox.c: In function ‘vos_material_box_set_child_property’:
lib/materialbox.c:333:21: warning: passing argument 1 of ‘g_value_set_int’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
     g_value_set_int(value, (gint)sheetInfo->location);
                     ^
In file included from /usr/include/glib-2.0/glib-object.h:36:0,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from /usr/include/gtk-3.0/gdk/gdkapplaunchcontext.h:28,
                 from /usr/include/gtk-3.0/gdk/gdk.h:32,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from lib/materialbox.h:25,
                 from lib/materialbox.c:20:
/usr/include/glib-2.0/gobject/gvaluetypes.h:199:13: note: expected ‘GValue \* {aka struct _GValue *}’ but argument is of type ‘const GValue \* {aka const struct _GValue *}’
 void        g_value_set_int  (GValue       *value,
             ^
lib/materialbox.c: In function ‘vos_material_box_show_sheet’:
lib/materialbox.c:445:28: warning: passing argument 1 of ‘gtk_widget_is_visible’ from incompatible pointer type [-Wincompatible-pointer-types]
   if(gtk_widget_is_visible(self))
                            ^
In file included from /usr/include/gtk-3.0/gtk/gtkapplication.h:27:0,
                 from /usr/include/gtk-3.0/gtk/gtkwindow.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkdialog.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from lib/materialbox.h:25,
                 from lib/materialbox.c:20:
/usr/include/gtk-3.0/gtk/gtkwidget.h:846:23: note: expected ‘GtkWidget \* {aka struct _GtkWidget *}’ but argument is of type ‘VosMaterialBox \* {aka struct _VosMaterialBox *}’
 gboolean              gtk_widget_is_visible             (GtkWidget    *widget);
                       ^
lib/materialbox.c:452:81: warning: passing argument 2 of ‘gtk_widget_add_tick_callback’ from incompatible pointer type [-Wincompatible-pointer-types]
 o->tickCallbackID = gtk_widget_add_tick_callback(GTK_WIDGET(sheet), sheet_anima
                                                                     ^
In file included from /usr/include/gtk-3.0/gtk/gtkapplication.h:27:0,
                 from /usr/include/gtk-3.0/gtk/gtkwindow.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkdialog.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from lib/materialbox.h:25,
                 from lib/materialbox.c:20:
/usr/include/gtk-3.0/gtk/gtkwidget.h:1317:7: note: expected ‘GtkTickCallback {aka int (_)(struct _GtkWidget _, struct _GdkFrameClock *, void *)}’ but argument is of type ‘gboolean (_)(VosMaterialSheet _, GdkFrameClock *, VosMaterialBoxSheetInfo *) {aka int (_)(struct _GtkWidget _, struct _GdkFrameClock *, struct <anonymous> *)}’
 guint gtk_widget_add_tick_callback (GtkWidget       *widget,
       ^
lib/materialbox.c: In function ‘vos_material_box_hide_sheet’:
lib/materialbox.c:482:28: warning: passing argument 1 of ‘gtk_widget_is_visible’ from incompatible pointer type [-Wincompatible-pointer-types]
   if(gtk_widget_is_visible(self))
                            ^
In file included from /usr/include/gtk-3.0/gtk/gtkapplication.h:27:0,
                 from /usr/include/gtk-3.0/gtk/gtkwindow.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkdialog.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from lib/materialbox.h:25,
                 from lib/materialbox.c:20:
/usr/include/gtk-3.0/gtk/gtkwidget.h:846:23: note: expected ‘GtkWidget \* {aka struct _GtkWidget *}’ but argument is of type ‘VosMaterialBox \* {aka struct _VosMaterialBox *}’
 gboolean              gtk_widget_is_visible             (GtkWidget    *widget);
                       ^
lib/materialbox.c:489:81: warning: passing argument 2 of ‘gtk_widget_add_tick_callback’ from incompatible pointer type [-Wincompatible-pointer-types]
 o->tickCallbackID = gtk_widget_add_tick_callback(GTK_WIDGET(sheet), sheet_anima
                                                                     ^
In file included from /usr/include/gtk-3.0/gtk/gtkapplication.h:27:0,
                 from /usr/include/gtk-3.0/gtk/gtkwindow.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkdialog.h:33,
                 from /usr/include/gtk-3.0/gtk/gtkaboutdialog.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:31,
                 from lib/materialbox.h:25,
                 from lib/materialbox.c:20:
/usr/include/gtk-3.0/gtk/gtkwidget.h:1317:7: note: expected ‘GtkTickCallback {aka int (_)(struct _GtkWidget _, struct _GdkFrameClock *, void *)}’ but argument is of type ‘gboolean (_)(VosMaterialSheet _, GdkFrameClock *, VosMaterialBoxSheetInfo *) {aka int (_)(struct _GtkWidget *, struct _GdkFrameClock *, struct <anonymous> *)}’
 guint gtk_widget_add_tick_callback (GtkWidget       *widget,
       ^
g-ir-scanner --include GObject-2.0 --include Gtk-3.0 --pkg gtk+-3.0\
    --pkg-export libvos --library-path /home/jerrick/graphene-desktop/lib --no-libtool\
  --identifier-prefix=Vos --symbol-prefix=vos --namespace Vos\
    --nsversion=1.0 --library vos --warn-all -o lib/Vos-1.0.gir lib/panel.c lib/applet-extension.c lib/system-volume-control.c lib/materialbox.c lib/panel.h lib/applet-extension.h lib/system-volume-control.h lib/materialbox.h
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to `pa_operation_unref'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to`pa_context_connect'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to `pa_proplist_free'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to`pa_strerror'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to `peas_extension_set_new'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to`peas_engine_enable_loader'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to `pa_context_get_state'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to`pa_glib_mainloop_get_api'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to `pa_glib_mainloop_new'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to`pa_context_subscribe'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to `peas_engine_get_plugin_list'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to`pa_context_set_sink_mute_by_index'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to `pa_context_new_with_proplist'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to`pa_proplist_sets'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to `pa_cvolume_scale'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to`peas_engine_rescan_plugins'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to `pa_context_set_subscribe_callback'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to`pa_context_set_state_callback'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to `peas_engine_add_search_path'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to`pa_context_unref'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to `peas_engine_get_default'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to`pa_context_set_sink_volume_by_index'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to `pa_context_get_sink_info_by_index'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to`peas_extension_set_foreach'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to `peas_plugin_info_get_module_name'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to`g_irepository_get_default'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to `pa_cvolume_max'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to`peas_engine_load_plugin'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to `pa_context_errno'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to`peas_plugin_info_is_builtin'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to `pa_glib_mainloop_free'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to`g_irepository_require'
/home/jerrick/graphene-desktop/lib/libvos.so: undefined reference to `pa_proplist_new'
collect2: error: ld returned 1 exit status
Caught exception: <class 'distutils.errors.LinkError'> LinkError(LinkError(DistutilsExecError("command 'x86_64-linux-gnu-gcc' failed with exit status 1",),),)

> /usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner/dumper.py(289)_link()
> -> raise LinkError(e)
> (Pdb)

**Comment by azsn** [comment]
It looks like you're missing the PulseAudio libraries. Try installing libpulse. If you're running on Arch, you should be able to run "sudo pacman -S libpulse". (Also, apologies for all the warnings on the build; I'll fix that eventually.)

**Comment by azsn** [comment]
Were you able to compile it?

**Comment by decorumos** [comment]
Nope going to compile all the dependencies from upstream source and will
check back in.
