### ISSUE TITLE
I could not run ubuntud if I had a bash, bin or run file instead of make. It would be good.

### ISSUE THREAD

**Issue by omerfeyyaz** [VeltTechnologies/graphene-desktop#11]
As I said in the title, I could not run ubuntuda if I had a bash, bin or run file instead of make. It would be good.

**Comment by azsn** [comment]
I'm sorry, I don't understand your issue. What is "ubuntud"? Do you mean Ubuntu?
Graphene Desktop is designed for Arch Linux, and may not run on other distros.

**Comment by omerfeyyaz** [comment]
Thanks for your help i tried on linux ubuntu if i liked it i will try it on my own operating system while my operating system is not finished yet. And how to make a desktop environment. Do you have any sources telling you how to add a panel or something?

**Comment by azsn** [comment]
Graphene (including its Panel) is written as a plugin for Mutter. However, if you want to only write a Panel (instead of a Window Manager), you can use GUI libraries such as GTK or Qt to create a Panel.

**Comment by omerfeyyaz** [comment]
Thank you
