### ISSUE TITLE
Graphene doesn't load?

### ISSUE THREAD

**Issue by TurnrDev** [VeltTechnologies/graphene-desktop#13]
I ran the instructions [here](https://velt.io/install-veltos/)

```
curl -fO https://velt.io/vosinstall.sh
chmod +x vosinstall.sh
sudo ./vosinstall.sh
```

However, whenever I attempt to load the Graphene Desktop Environment it just sits at black for half a second and takes me back to the log-in screen.

**Comment by FredBezies** [comment]
It is normal. Looks like packages were not build againt new mutter where libmutter-1.so is no longer available...

**Comment by azsn** [comment]
I fixed the mutter issue (and some other stuff). I'll update graphene on the repo hopefully tomorrow, I don't have time to mess with that today. Thank you FredBezies, and sorry for not taking your pull request; I wanted to update the version number to the minimum that needed libmutter-2 anyway.

**Comment by FredBezies** [comment]
@zelbrium my commit was just a dirty fix for this long term bug.
