### ISSUE TITLE
No way to maximize applications

### ISSUE THREAD

**Issue by Secris** [VeltTechnologies/graphene-desktop#5]
Pretty self explanatory. 
By default gnome3 applications do not have minimize or maximize buttons. We should probably implement the ability to control these in the future settings tool.

**Comment by azsn** [comment]
This is configurable with GSettings (can use dconf-editor). See the /org/gnome/desktop/wm/preferences/button-layout key. Gnome Control Center (current default settings tool) does not have an option to configure this setting, however the Graphene Panel's settings sidebar will probably have that option eventually.
